#!/usr/bin/perl

# DynamicMTML (C) 2010-2011 Alfasado Inc.
# This program is distributed under the terms of the
# GNU General Public License, version 2.

use strict;
use lib qw( lib extlib addons/DynamicMTML.pack/lib );
use MT;
my $mt = MT->new();
use DynamicMTML::WeblogPublisher;
use MT::FileInfo;
my $id    = $ARGV[0];
my $key   = $ARGV[1];
my $force = $ARGV[2];
my $pub   = DynamicMTML::WeblogPublisher->new;
my $fi    = MT::FileInfo->load( $id );
if (! $force ) {
    my $map_id = $fi->templatemap_id;
    my $tmpl_id = $fi->template_id;
    if ( $map_id ) {
        my $map = MT::TemplateMap->load( $map_id );
        if ( $map ) {
            return unless $map->build_type;
        }
    } elsif ( $tmpl_id ) {
        my $tmpl = MT::Template->load( $tmpl_id );
        if ( $tmpl ) {
            return unless $tmpl->build_type;
        }
    }
}
$pub->rebuild_from_fileinfo( $fi, $key );